### ISSUE TITLE
Единицы измерения eV_m, eV_T

### ISSUE THREAD

**Issue by temafox** [kononovarseniy/fompy#18]
Код из примеров не работает, так как не распознаются единицы eV_m, eV_T.

`s = Semiconductor(me_eff= 0.1 * unit('MeV_m'), mh_eff= 4. * 10**(-28), Eg= 1. * unit('eV'))`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tema/.local/lib/python3.9/site-packages/fompy/units.py", line 180, in unit
    return parse_unit(text).get_number()
  File "/home/tema/.local/lib/python3.9/site-packages/fompy/units.py", line 133, in parse_unit
    ts = TokenList(filter(lambda t: t[0] != 'optional', TOKENIZER.tokenize(text)))
  File "/home/tema/.local/lib/python3.9/site-packages/fompy/util/parser.py", line 59, in __init__
    super().__init__(tokens)
  File "/home/tema/.local/lib/python3.9/site-packages/fompy/util/parser.py", line 46, in tokenize
    raise SyntaxError(f'Tokenizer stopped at position {pos}')
SyntaxError: Tokenizer stopped at position 3

**Comment by kononovarseniy** [comment]
Забавно, что надо было добавить лишь один символ в код.
